package com.example.data

import com.example.data.api.ParkApi
import com.example.data.qualifiers.AutogeneratedRetrofitClient
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import retrofit2.create
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
class ApiModule {
    @Provides
    @Singleton
    fun provideParkingSpotsApi(@AutogeneratedRetrofitClient retrofit: Retrofit): ParkApi = retrofit.create()

}